
server:
    port: 9000
management:
    address: 127.0.0.1
    port: 9100
logging:
    level:
        application: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/kenshu
        username: postgres
        password: admin
        driverClassName: org.postgresql.Driver
    messages:
        encoding: UTF-8
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: localhost
        password:
        port: 6379
security:
    user:
        name: manager
        password: ziNYWtS58L8A
    basic:
        enabled: false
        
line:
    bot:
        channelToken: PANfDZSDDHZ3hewB4OjV0VwzMlyBRWZfn1dM/7CpOdXi4nF9OaYSe/5WYp9IgN4Re/jzROCi6zhST1NMDqlHDPwJMNnS7NaLvD/CWFGdhGe8VvT56CEZNXBhnLuL9QqfcUVxU+nQU0XHaZTvqpakswdB04t89/1O/w1cDnyilFU=
        channelSecret: 0f07aa535865f13a2a7ba0e3a1367d22
    linelogin:
        channelId: 1561281540
        channelSecret: b4a6b6d9da1bfeac94206a4a1a81c29b
        callbackUrl: https://8ce04262.ngrok.io/user/auth