server:
    port: 9000
management:
    address: 127.0.0.1
    port: 9100
logging:
    level:
        application: DEBUG
        org.springframework.jdbc.core.JdbcTemplate: DEBUG
spring:
    datasource:
        url: jdbc:oracle:thin:ATT_USER/att_user@//192.168.56.101:1521/ORCL
        driverClassName: oracle.jdbc.driver.OracleDriver
    messages:
        encoding: UTF-8
    thymeleaf:
        cache: false
    session:
        store-type: redis
    redis:
        host: localhost
        password:
        port: 6379
    mvc:
        media-types:
          csv:  text/csv
security:
    user:
        name: manager
        password: ziNYWtS58L8A
    basic:
        enabled: false
line:
    bot:
        lineAtId: '@fjp2603q'
        channelToken: jjEAxDf5JSKXe3AOYwo/kaaQuXdmF35USypCTQIoM3dsRxRz9ao5Ek9FUsKjKlJ4g+Je+3AtuXdfIRuJDlURVyGLXNK8ZhNT1ra7Kxu+W5sVJg9oe4DvMsSgmmnySAqB6dpPRUlNQdW84OXwM+/ErQdB04t89/1O/w1cDnyilFU=
        channelSecret: 59be071d3ca46f4bfb7c2aa7f79c4c2d
    linelogin:
        channelId: 1565512921
        channelSecret: e6cc7c1964ef1f62b0aee3db28aa1a09
        callbackUrl: https://469d3b1e.ngrok.io/user/auth